apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-restore
  namespace: demo
spec:
  addon:
    name: workload-addon
    tasks:
      - name: LogicalBackupRestore
  dataSource:
    components:
      - pod-0
      - pod-2
    encryptionSecret:
      name: encrypt-secret
      namespace: demo
    repository: gcs-demo-repo
    snapshot: latest
  target:
    apiGroup: apps
    kind: StatefulSet
    name: restore-sts
    namespace: demo
status:
  components:
    pod-0:
      duration: 10.089085545s
      phase: Succeeded
    pod-2:
      duration: 6.509171185s
      phase: Succeeded
  conditions:
    - lastTransitionTime: "2023-12-18T09:13:35Z"
      message: Validation has been passed successfully.
      reason: ResourceValidationPassed
      status: "True"
      type: ValidationPassed
    - lastTransitionTime: "2023-12-18T09:13:36Z"
      message: Restore Executor has been ensured successfully.
      reason: SuccessfullyEnsuredRestoreExecutor
      status: "True"
      type: RestoreExecutorEnsured
    - lastTransitionTime: "2023-12-18T09:13:59Z"
      message: Metrics have been pushed successfully.
      reason: SuccessfullyPushedMetrics
      status: "True"
      type: MetricsPushed
  dependencies:
    - found: true
      kind: Snapshot
      name: gcs-demo-repo-sample-backup-sts-demo-session-1702543201
      namespace: demo
    - found: true
      kind: Addon
      name: workload-addon
  duration: 25s
  phase: Succeeded
  targetFound: true
  totalComponents: 2