apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: demo
type: Opaque
stringData:
  username: doadmin # replace with your auth username
  password: "" # <replace with your authentication password>