apiVersion: v1
kind: ServiceAccount
metadata:
  name: permissions-serviceaccount
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubestash-backup-job
  namespace: demo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]  
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubestash-backup-job-rolebinding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: permissions-serviceaccount
    namespace: demo
roleRef:
  kind: Role
  name: kubestash-backup-job
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubestash-retention-policy-job
  namespace: demo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]  
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubestash-retention-policy-job-rolebinding
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: permissions-serviceaccount
    namespace: demo
  - kind: ServiceAccount
    name: my-app-restoresession
    namespace: demo
roleRef:
  kind: Role
  name: kubestash-retention-policy-job
  apiGroup: rbac.authorization.k8s.io
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-clusterrole 
  namespace: demo
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]  
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permission-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: permissions-serviceaccount
    namespace: demo
  - kind: ServiceAccount 
    name: my-app-restoresession 
    namespace: demo 
roleRef:
  kind: ClusterRole
  name: permission-clusterrole 
  apiGroup: rbac.authorization.k8s.io