apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: my-mysql
  namespace: db
spec:
  version: "8.1.0"  
  replicas: 3
  topology:
    mode: GroupReplication
  storageType: Durable
  storage:
    storageClassName: "default"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut
