apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: restic-cache-volume
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: Deployment
    name: kubestash-demo
    namespace: demo
  backends:
    - name: gcs-backend
      storageRef:
        name: gcs-storage
        namespace: demo
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: demo-session
      scheduler:
        schedule: "*/5 * * * *"
      repositories:
        - name: gcs-demo-repo
          backend: gcs-backend
          directory: /dep
          encryptionSecret:
            name: encrypt-secret
            namespace: demo
      addon:
        name: workload-addon
        tasks:
          - name: logical-backup
            addonVolumes:
              - name: ${RESTIC_CACHE_VOLUME}
                source:
                  volumeClaimTemplate:
                     spec:
                       accessModes:
                       - ReadWriteOnce
                       resources:
                         requests:
                           storage: 1Gi